Repository HimoJuku/HimoJuku, pull requests merged in 2025-04, with the labels that each got.

#3 Import Reader
  .idea/.gitignore
  app/(tabs)/reader.tsx
  app/_layout.tsx
  app/bookManagement/index.tsx
  components/CustomDrawerContent.tsx
  package-lock.json
  package.json
Labels: enhancement

#4 settings page ui
  app/_layout.tsx
  app/settings/index.tsx
  package.json
Labels: enhancement

#8 Feat: Update Book Management Module, Improve EPUB Parsing Logic; Integrate Database for Book Metadata Storage.
  app.json
  app/(tabs)/reader.tsx
  app/DatabaseTest/index.tsx
  app/_layout.tsx
  app/book/type.ts
  app/bookManagement/epubParser.ts
  app/bookManagement/index.tsx
  app/bookShelf/index.tsx
  assets/images/cover-placeholder.png
  db/Book.ts
  db/index.ts
  db/schema.ts
  package-lock.json
  package.json
  tsconfig.json
Labels: enhancement

#5 feat: add txt2epub dependency and implement txt to epub conversion
  .gitignore
  app/_layout.tsx
  app/book/type.ts
  app/bookManagement/index.tsx
  app/txt2epub/converter.ts
  app/txt2epub/type.ts
  package-lock.json
  package.json
Labels: enhancement

#12 feat: add database support for settings
  .gitignore
  README.md
  app/DatabaseTest/index.tsx
  app/_layout.tsx
  app/book/type.ts
  app/bookManagement/_epubParser.ts
  app/bookManagement/index.tsx
  app/bookShelf/index.tsx
  app/bookShelf/sort.ts
  app/settings/index.tsx
  app/txt2epub/converter.ts
  components/CustomDrawerContent.tsx
  constants/Colors.ts
  constants/books.ts
  constants/settings.ts
  constants/txtBooks.ts
  db/index.ts
  db/models/books.ts
  db/models/configs.ts
  db/models/settings.ts
  db/schema.ts
  hooks/useThemeColor.ts
  package.json
  scripts/reset-project.js
Labels: enhancement

#14 hotfix: depends
  package.json
Labels: bug

#15 feat: Implement Navigation systems
  app/(drawer)/_layout.tsx
  app/(drawer)/bookManagement.tsx
  app/(drawer)/bookShelf.tsx
  app/(drawer)/databaseTest.tsx
  app/(drawer)/settings.tsx
  app/DatabaseTest/index.tsx
  app/_layout.tsx
  app/reader.tsx
  app/search.tsx
  components/CustomDrawerContent.tsx
  components/Gradient.tsx
  components/Header.tsx
  db/index.ts
  db/models/Chapter.ts
  db/schema.ts
  functions/_epubParser.ts
  functions/sort.ts
  hooks/useThemeColor.ts
  package.json
  txt2epub/converter.ts
Labels: bug, enhancement

#17 hotfix
  app/(drawer)/_layout.tsx
  app/(drawer)/index.tsx
Labels: bug

#18 feat: added reader settings (Header & Footer); improved parsing with chapter support
  app/(drawer)/databaseTest.tsx
  app/_layout.tsx
  app/reader.tsx
  app/reader/Footer.tsx
  app/reader/Header.tsx
  app/reader/TOC.tsx
  app/reader/index.tsx
Labels: enhancement
